# Generated by Django 3.0.7 on 2020-09-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endApi', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
