# Generated by Django 3.0.7 on 2020-09-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endApi', '0004_auto_20200903_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default='2013-02-23 12:34'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='rajielijah@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
