# Generated by Django 3.0.7 on 2020-09-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endApi', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/feedupload'),
        ),
    ]
