# Generated by Django 3.0.7 on 2020-09-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endApi', '0008_auto_20200904_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='endApi.Post'),
            preserve_default=False,
        ),
    ]
