# Generated by Django 3.0.7 on 2020-09-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endApi', '0009_profile_user_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='oke aro', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='nigeria', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='lagos', max_length=30),
            preserve_default=False,
        ),
    ]
