# Generated by Django 3.0.7 on 2020-09-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endApi', '0011_profile_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
