# Generated by Django 3.0.7 on 2020-09-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endApi', '0012_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_posts',
        ),
    ]
