# Generated by Django 3.0.7 on 2020-09-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endApi', '0017_auto_20200908_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='product_description',
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default='1000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='product_details',
            field=models.TextField(default='hmm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='product_name',
            field=models.CharField(default='hairs', max_length=200),
            preserve_default=False,
        ),
    ]
