# Generated by Django 3.0.7 on 2020-09-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endApi', '0020_auto_20200909_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(default='09036475407', max_length=11),
            preserve_default=False,
        ),
    ]
