# Generated by Django 3.0.7 on 2020-09-11 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('endApi', '0021_profile_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
