# Generated by Django 3.0.7 on 2020-09-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endApi', '0023_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
