# Generated by Django 3.0.7 on 2020-09-13 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endApi', '0031_auto_20200913_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='endApi.Profile'),
        ),
    ]
