# Generated by Django 3.0.7 on 2020-09-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endApi', '0037_auto_20200916_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='emails',
        ),
    ]
