# Generated by Django 3.0.7 on 2020-09-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endApi', '0038_auto_20200918_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emails',
        ),
    ]
