# Generated by Django 3.0.7 on 2020-09-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endApi', '0040_auto_20200919_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emails',
            new_name='email',
        ),
    ]
