# Generated by Django 3.0.7 on 2020-09-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endApi', '0041_auto_20200919_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='user',
        ),
    ]
